### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by AntonioAhn** [cfce/chilin#12]
Hello :) 

ChiLin looks like a great pipeline and i would love to use it. 

Currently, i get an error: 

> error: unrecognized arguments: -f 
usage: setup.py [list|install]
Time-stamp: <2014-11-13 09:38:31 qqin>
install ChiLin and related program and dependent data
positional arguments:
  install     install chilin
optional arguments:
  -h, --help  show this help message and exit

when running: 
`python setup.py install -f`

Would you be able to put me in the right track with this please? 

Thank you,
Antonio

**Comment by qinqian** [comment]
Hello:

Now we have a conda installation protocol, please follow the `install_with_conda.sh` to have a try. After setting up the conda environment, please run `python setup.py install`. We will also release a docker version soon. Thanks for your interest.

Best,
Qian

**Comment by qinqian** [comment]
Hello,

We now have a docker version, if you have docker or singularity installed, please give it a try at https://github.com/cfce/chilin/. 

Best,
Qian
