### ISSUE TITLE
trimmomatic

### ISSUE THREAD

**Issue by ansheng0** [cfce/chilin#15]
Hello:
When I run program chilin, do I need to run program trimmomatic first？

Thank you
Li

**Comment by qinqian** [comment]
Hello:

Please take a look at the second version of the (https://github.com/liulab-dfci/CHIPS), they use a fastp (https://github.com/liulab-dfci/CHIPS/blob/main/modules/trim_adapter.snakefile) to trim the adapter. 

Best,
Qian
