### ISSUE TITLE
Got {id}_control.bw even though no control replicated were fed in.

### ISSUE THREAD

**Issue by WJH58** [cfce/chilin#16]
Hi! I ran this pipeline without any control fastq files but at last I got {id}_control.bw and {id}_treat.bw. I left "cont =" line in the config file blank. Is there any explanation? Thanks!

**Comment by qinqian** [comment]
Yes, if a control sample was not given, this will be randomly simulated from the ChIP-seq data by MACS2 to generate the background control signal (bed graph), and then convert to bigwig.

**Comment by WJH58** [comment]
Thank you for your reply!
