### ISSUE TITLE
Cannot Find Command chilin

### ISSUE THREAD

**Issue by christacaggiano** [cfce/chilin#3]
Hi everyone,

I followed all of the steps to install chilin.
However, after I source the virtual environment, when I try to run chilin -h, it says 
`(chilin_env)[ccag@ares bin]$ chilin
-bash: chilin: command not found
`

What might have happened here?

**Comment by qinqian** [comment]
The issue is caused by the virtualenv and setuptools on older system, which lead to `sys_platform` or `src_root` problem. We have tried to fix this, pull the latest version of chilin. Then, rerun the installation with following,

``` python
sudo pip2.7 uninstall distribute 
sudo pip2.7 install -U pip
sudo pip2.7 install setuptools -U
sudo pip2.7 install -U virtualenv
cd chilin
rm -rf chilin_env
python2.7 setup.py install -f
source chilin_env/bin/activate
#for centos
sudo yum install lzo-devel
#for ubuntu
sudo apt-get install liblzo2-dev
pip2.7 install python-lzo
python2.7 setup.py install
```
