### ISSUE TITLE
My ChiLin cannot find .tex files

### ISSUE THREAD

**Issue by kumanuke** [cfce/chilin#5]
I have some troubles with running chilin.

When I tried demo/foxa1 using bash command, I could get the final pdf file.
Next, I tried the command:
chilin  simple -p narrow -t foxa1_t1.fastq  -c foxa1_c1.fastq -i local -o local -s hg19  --skip 10,12 --dont_remove

it says
cat: /Users/macbookairf6t6/chilin/local/latex/local_fastqc.tex: No such file or directory

and the command line would stop after displaying some "LaTeX Warning".

I think there would be something wrong with my MacTex settings..
How can I solve the problem? 

Thanks.

**Comment by qinqian** [comment]
Thanks for the feedback! Is the QC report generated? Can you paste the full log file here? I thought the issue is caused by missing fastqc result. Try to check whether the fastqc is in PATH or not.
