### ISSUE TITLE
demo bash (demo foxa1) running error and failed 

### ISSUE THREAD

**Issue by zhenyisong** [cfce/chilin#6]
I used root privilege to install the package.
There is a typo in the installation protocol:
```
md5sum -c hg19.tgz
```
should be 

```
md5sum -c hg19.tgz.md5
```
Anyway, there was no failure message during installation.

However, when I run the demo (bash foxa1), the throw-out error was:
```
[main] CMD: bwa samse /bioware/chilin/db/mycoplasma.fasta /bioware/chilin/demo/local/local_control_rep2mycoplasma.sai /bioware/chilin/demo/local/local_control_rep2_100k.fastq
[main] Real time: 0.126 sec; CPU: 0.125 sec
[samopen] SAM header is present: 1 sequences.
[samopen] SAM header is present: 1 sequences.
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index

[bwa_sai2sam_se] fail to locate the index
[main_samview] fail to open "/bioware/chilin/demo/local/local_treat_rep1.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_treat_rep2.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_control_rep1.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_control_rep2.sam" for reading.

```

And asked me repeatedly to input the file name:

```
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(/bioware/chilin/demo/local/local_report.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
aded.
(/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
Document Class: report 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))

! LaTeX Error: File `fullpage.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: temp3
```

I think the latter case is to call Latex to output result in PDF format? because the previous step, the error was thrown-out, then the pipeline gave its complaint. Any suggestions?

**Comment by qinqian** [comment]
Thanks for the feedback. please try to install the tex package http://www.ctan.org/pkg/fullpage into tex search path.

**Comment by zhenyisong** [comment]
The bug is creeping out:

```
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index
[main_samview] fail to open "/bioware/chilin/demo/local/local_treat_rep1.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_treat_rep2.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_control_rep1.sam" for reading.
[main_samview] fail to open "/bioware/chilin/demo/local/local_control_rep2.sam" for reading.
['/bioware/chilin/demo/local/local_control_rep1', '/bioware/chilin/demo/local/local_control_rep2']
cat: /bioware/chilin/demo/local/latex/local_map.tex: No such file or directory
cat: /bioware/chilin/demo/local/latex/local_conserv.tex: No such file or directory
cat: /bioware/chilin/demo/local/latex/local_motif.tex: No such file or directory
cat: /bioware/chilin/demo/local/latex/local_frip.tex: No such file or directory
```
The demo tried to find the index file, and generate the sam for the downstream output. However, the required index was not on-the-fly generated or the path for the hg19 index was mis-configured. So the sam file in the 'local' dir (running demo, bash foxa1) led to zero size sam result files.

Besides, the ChinLin package needs the full version of Latex supporting packages. I think at least in the Centos (7), this is required manually to install the required package one by one. I used the 
``` 
yum install 'texlive-*'
```
 and still the system complained that a  lot of packages were needed to install to proceed. This really consumed me a lot of energy.

Please let me know how to proceed. Thanks in advance.

**Comment by qinqian** [comment]
Try to follow the instructions here: 

1. download the genome index here the link here http://cistrome.org/chilin/Appendix.html#get-dependent-data; 
2. fill in the genome index https://github.com/cfce/chilin/blob/master/chilin.conf or chilin.conf.filled in the root directory of the ChiLin code, and reinstall ChiLin; 
3. install all of the latex modules with
``` bash
 yum install texlive-scheme-full
```

Sorry for the inconvenience.

**Comment by zhenyisong** [comment]
I reinstalled the package. However, my system is Centos.7 and the required package (texlive-scheme-full) is not maintained at present. (Fedora might be supported) This is very inconvenient. Anyway, is there any plain analysis report (or matrices) so I can use other program to parse them? The local output has huge amount of intermediary data. Thanks.

**Comment by zhanghao-njmu** [comment]
@zhenyisong you should manually install TeX Live following https://www.tug.org/texlive/quickinstall.html
It works for me on centos7.

**Comment by zhenyisong** [comment]
@zh542370159 Thanks. I did not go through this. And @qinqian  should join the conda maintenance line, this will definitely leverage up its usage.
