### ISSUE TITLE
Not generating .bam files

### ISSUE THREAD

**Issue by darrylyan46** [cfce/chilin#7]
Hi, I was trying to run chilin on a new sample with the following command:
```
chilin simple -s hg38 --threads 8 -i BCL3_t00 -o BCL3_t00 -t ${sample} 
-c ${ctrl} --dont_remove -p narrow 2>&1
```

The program runs through but only completes the FastQC steps. I looked at the log and found the following:

![image](https://user-images.githubusercontent.com/14950752/27880486-1aa381ba-6193-11e7-8155-472a1c4df929.png)

This happens occurs every instance where there is a .bam file attempted to be read where there is an empty line followed by:
```
Missing inputs ['/gpfs/fs0/data/reddylab/Darryl/BCL3_t00/BCL3_t00_treat_rep1mycoplasma.bam']
```
Perhaps there is an issue generating the .bam files? I believe I have the correct dependencies and version of *samtools (version 1.3.1). If you could shed some light on this issue I would appreciate it.

**Comment by qinqian** [comment]
The bwa genome index for mycoplasma should be filled in the conf file section.
